### ISSUE TITLE
drive.info on windows throws error

### ISSUE THREAD

**Issue by dougroutledge** [SunilWang/node-os-utils#1]
On any machine I have tested, drive.info throws "disk name invalid and / not found".  Even on Vm with single drive.

**Comment by SunilWang** [comment]
@dougroutledge 
“drive.info” default “disk name” is "/"
or
drive.info("/dev")

**Comment by dougroutledge** [comment]
so what is the proper syntax on windows, drive.info("C:") ?

**Comment by SunilWang** [comment]
sorry, not support "windows" system.
