### ISSUE TITLE
mem.info totalMemMb on Windows 10 returns GBs

### ISSUE THREAD

**Issue by fcharron** [SunilWang/node-os-utils#13]
**Platform**: Windows 10.0.19041 x64

**Result**:
TotalMem: 16978169856
TotalMemMb: 15.81

**Expected**: 16191.64MB

--

I'm guessing since .oos() reports "NOT_SUPPORTED", I'm hitting the extra /1024 at https://github.com/SunilWang/node-os-utils/blob/069f9cf51796564e950ede8a2a7251e990cbab43/lib/mem.js#L127, when I shouldn't.

**Comment by SunilWang** [comment]
https://github.com/SunilWang/node-os-utils/blob/069f9cf51796564e950ede8a2a7251e990cbab43/lib/mem.js#L128

L127 and L128 should have problems，Can you verify it for me?

**Comment by SunilWang** [comment]
fix！

https://www.npmjs.com/package/node-os-utils

```sh
npm install node-os-utils@1.3.2
```
@fcharron 
Thank you ~

**Comment by fcharron** [comment]
Thanks for the quick response! I just tried it and it works great :)
