### ISSUE TITLE
空闲内存计算错误

### ISSUE THREAD

**Issue by AndrewGoal** [SunilWang/node-os-utils#3]
https://github.com/SunilWang/node-os-utils/blob/64d8e1e957de1192cd76c5b9b018c2daaf41f09b/lib/mem.js#L76

应该是：
```javascript
freeMem = (parseInt(resultMemory[1], 10) + parseInt(resultMemory[3], 10) + parseInt(resultMemory[4], 10)) * 1024
```
括号不对，导致计算有误

**Comment by SunilWang** [comment]
Fix free memory calculation equation.

https://github.com/SunilWang/node-os-utils/pull/4
