### ISSUE TITLE
Not support get network on Mac OS

### ISSUE THREAD

**Issue by taihoa** [SunilWang/node-os-utils#35]
I using on Mac OS. But It not support get info network
Please help me!

**Comment by SunilWang** [comment]
mac os  not support `ip -s link` command.

**Comment by taihoa** [comment]
> mac os not support `ip -s link` command.
How to can you get info network on Mac?
Do you have solution?

**Comment by SunilWang** [comment]
@taihoa I'm sorry. I don't have any good ideas, okay

**Comment by taihoa** [comment]
> @taihoa I'm sorry. I don't have any good ideas

Thank you!
