### ISSUE TITLE
Command failed: sysctl hw.memsize\n/bin/sh: sysctl: command not found\n in mac

### ISSUE THREAD

**Issue by lyouthzzz** [SunilWang/node-os-utils#6]
var mem = osu.mem;
mem.used().then(info => {
  console.log(info);
};
![image](https://user-images.githubusercontent.com/29134871/71430731-88689b80-2708-11ea-9a45-39c6a16b725c.png)

because bucket.exec('sysctl hw.memsize') error happened

**Comment by SunilWang** [comment]
`bucket.exec`  为了模块安全，防止远程攻击，这个方法已经废弃了。

`mem.used()` 这个方法可以正常使用。
